import { AnimatePresence, motion, useReducedMotion } from "framer-motion";

import { pizzaStudioExtras, type PizzaStudioExtra } from "@/lib/food/pizza-studio-catalogue";
import { pizzaSizeScale } from "@/lib/food/pizza-studio-visual-model";
import { MealCompanionTray } from "./meal-companion-tray";
import { ParkyGuide } from "./parky-guide";
import { PizzaToppingLayer } from "./pizza-topping-layer";

export function PizzaCanvas({ sizeId, sizeName, inches, crustId, sauceId, cheeseId, toppingIds, extraIds, step, fullHouseComplete }: { sizeId:string;sizeName:string;inches:number;crustId:string;sauceId:string;cheeseId:string;toppingIds:string[];extraIds:string[];step:string;fullHouseComplete:boolean }) {
  const reduceMotion=useReducedMotion(); const extras=extraIds.map(id=>pizzaStudioExtras.find(item=>item.id===id)).filter((item):item is PizzaStudioExtra=>Boolean(item));
  const broccoli=crustId==="broccoli-vegan-base"; const vegan=cheeseId==="vegan-cheese";
  return <div className="overflow-hidden rounded-[2rem] bg-[#07101f] text-white shadow-[0_30px_80px_rgba(15,23,42,.24)]"><div className="relative overflow-hidden px-5 pb-7 pt-6 sm:px-6"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-orange-500/20 blur-3xl"/><div className="relative flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-orange-400">Live meal canvas</p><h2 className="mt-2 text-2xl font-black">Watch it come alive.</h2></div><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-bold text-white/70">LIVE</span></div><div className="relative mx-auto mt-5 aspect-square w-full max-w-[350px]" aria-label={`${inches} inch ${sizeName} pizza with ${toppingIds.length} selected toppings`}><div className="absolute inset-[4%] rounded-full bg-black/35 blur-xl"/><motion.div animate={{scale:pizzaSizeScale[sizeId]??.94,rotate:reduceMotion?0:toppingIds.length*.35}} transition={{type:"spring",stiffness:160,damping:20}} className={`absolute inset-0 rounded-full border-[16px] shadow-[inset_0_0_0_5px_rgba(255,255,255,.1),0_24px_50px_rgba(0,0,0,.35)] ${broccoli?"border-[#638347] bg-[#8eaa58]":"border-[#b85d21] bg-[#e99a42]"}`}><motion.div key={sauceId} initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} className="absolute inset-[5%] rounded-full bg-[#d94d2f]"/><motion.div key={cheeseId} initial={{opacity:0}} animate={{opacity:1}} className={`absolute inset-[9%] rounded-full shadow-inner ${vegan?"bg-[#f6e8a8]":"bg-[#f4d06f]"}`}/><AnimatePresence><PizzaToppingLayer toppingIds={toppingIds}/></AnimatePresence>{fullHouseComplete&&!reduceMotion?<span className="absolute inset-0 animate-pulse rounded-full ring-4 ring-yellow-300/50" aria-hidden="true"/>:null}</motion.div><div className="absolute bottom-0 left-1/2 -translate-x-1/2 rounded-full bg-white px-4 py-2 text-xs font-black text-slate-950 shadow-xl">{inches}&quot; {sizeName}</div></div><MealCompanionTray extras={extras}/><ParkyGuide step={step} toppingCount={toppingIds.length} fullHouseComplete={fullHouseComplete} hasNaturalJuice={extras.some(item=>item.category==="natural-juice")}/></div></div>;
}
