#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/d205ef1403e0f10a670c92541aaed7924cdbffe59df1a1c35c6b1215c52c1fbd/contract';
import endContract from '../../snapshots/d205ef1403e0f10a670c92541aaed7924cdbffe59df1a1c35c6b1215c52c1fbd/contract.json' with { type: 'json' };
import {
  Migration,
  MigrationCLI,
  checkExpression,
  col,
  fn,
  lit,
  primaryKey,
} from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createTable({
        schema: 'public',
        table: 'admission_package_features',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('label', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('packageId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('sortOrder', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'admission_packages',
        columns: [
          col('adultPriceMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('badge', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('childPriceMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('JMD'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isActive', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('isFeatured', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('maxGuests', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('minGuests', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('slug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sortOrder', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('validFrom', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('validUntil', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'bookingAdmissionFulfillment',
        columns: [
          col('accessIssuedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('bookingId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('passesIssuedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('paymentReference', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('providerEventId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'bookingPassAccess',
        columns: [
          col('accessCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('bookingId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('expiresAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('lastAccessedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('tokenHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'bookingPassAccessSecret',
        columns: [
          col('accessId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('authenticationTag', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('encryptedToken', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('initializationVector', 'text', {
            notNull: true,
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('keyVersion', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'bookingPassCredential',
        columns: [
          col('authenticationTag', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('encryptedCredential', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('initializationVector', 'text', {
            notNull: true,
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('keyVersion', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('passId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'bookingPassSecurityEvent',
        columns: [
          col('action', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('bookingId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('newVersion', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('passId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('performedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('performedByName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('previousVersion', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('reason', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'booking_events',
        columns: [
          col('actorId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('actorType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('bookingId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'booking_extra_definitions',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('JMD'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isActive', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('maxQuantity', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('priceMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('pricingMode', 'text', {
            notNull: true,
            default: lit('per_booking'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('slug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sortOrder', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'booking_extra_definitions_pricingMode_check_9498960a',
            "\"pricingMode\" IN ('per_booking', 'per_guest')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'booking_extras',
        columns: [
          col('bookingId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('currency', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('definitionId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('extraDescription', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('extraName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('extraSlug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('pricingMode', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('quantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('subtotalMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('unitPriceMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'booking_extras_pricingMode_check_9498960a',
            "\"pricingMode\" IN ('per_booking', 'per_guest')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'booking_guests',
        columns: [
          col('bookingId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('guestType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('subtotalMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('unitPriceMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'booking_guests_guestType_check_cec0f8ca',
            "\"guestType\" IN ('adult', 'child')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'booking_package_snapshots',
        columns: [
          col('admissionPackageId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('adultQuantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('adultUnitPriceMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('bookingId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('childQuantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('childUnitPriceMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('currency', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('packageDescription', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('packageName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('packageSlug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('subtotalMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'booking_passes',
        columns: [
          col('bookingId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('firstUsedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('guestType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('passNumber', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('qrTokenHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('revokeReason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('sequenceNumber', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('active'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('tokenVersion', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('validDate', 'date', { notNull: true, codecRef: { codecId: 'pg/date-temporal@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'booking_passes_guestType_check_cec0f8ca',
            "\"guestType\" IN ('adult', 'child')",
          ),
          checkExpression(
            'booking_passes_status_check_ed032e1f',
            "\"status\" IN ('active', 'used', 'revoked', 'cancelled', 'expired')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'bookings',
        columns: [
          col('admissionSubtotalMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('adultCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('cancellationReason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('cancelledAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('childCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('confirmationSentAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('JMD'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('customerEmail', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('customerFirstName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('customerId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('customerLastName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('customerPhone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('discountMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('expiresAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('extrasSubtotalMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('guestCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('paymentStatus', 'text', {
            notNull: true,
            default: lit('pending'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('reference', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('draft'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('taxMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('totalMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('visitDate', 'date', { notNull: true, codecRef: { codecId: 'pg/date-temporal@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'bookings_paymentStatus_check_93aac780',
            "\"paymentStatus\" IN ('not_required', 'pending', 'authorized', 'paid', 'failed', 'partially_refunded', 'refunded')",
          ),
          checkExpression(
            'bookings_status_check_dea2fe8e',
            "\"status\" IN ('draft', 'pending_payment', 'confirmed', 'partially_checked_in', 'checked_in', 'completed', 'cancelled', 'expired', 'refunded')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'check_ins',
        columns: [
          col('bookingId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('checkedInById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('checkedInByName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('deviceId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('gate', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('passId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('scannedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('status', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'check_ins_status_check_7067e93e',
            "\"status\" IN ('accepted', 'rejected', 'already_used', 'invalid', 'revoked')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'happy_ticket_ledger',
        columns: [
          col('businessKey', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('classId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('createdById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('orderId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('reason', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('schoolId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'happy_ticket_ledger_type_check_597db84e',
            "\"type\" IN ('order_earn', 'volume_bonus', 'manual_adjustment', 'reward_redemption', 'reversal', 'promotion')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_classes',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('grade', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isActive', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('schoolId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('teacherDisplayName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_contacts',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isActive', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('isPrimary', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('role', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('schoolId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('telephone', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_invoices',
        columns: [
          col('currency', 'text', {
            notNull: true,
            default: lit('JMD'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('deliveryMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('discountMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('dueAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('idempotencyKey', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('invoiceNumber', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('issuedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('orderId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('paidMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('schoolId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('invoiced'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('subtotalMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('taxMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('totalMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'school_invoices_status_check_4486af05',
            "\"status\" IN ('unbilled', 'invoiced', 'due_on_delivery', 'paid', 'partially_paid', 'overdue', 'void')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_order_class_allocations',
        columns: [
          col('classId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('orderId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('pizzaBoxes', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_order_lines',
        columns: [
          col('batchSize', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('category', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('currency', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('orderId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('productDescription', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('productId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('productName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('productSlug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('quantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('subtotalMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('unitPriceMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'school_order_lines_category_check_f344fea7',
            "\"category\" IN ('pizza', 'batch')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_orders',
        columns: [
          col('cancelledAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('confirmedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('JMD'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('deliveredAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('deliveredBy', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('deliveryAddress', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('deliveryContactName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('deliveryInstructions', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('deliveryMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('deliveryNote', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('deliveryTelephone', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('deliveryWindow', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('discountMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('idempotencyKey', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('paymentStatus', 'text', {
            notNull: true,
            default: lit('unbilled'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('paymentTerms', 'text', {
            notNull: true,
            default: lit('pay_on_delivery'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('pizzaFriday', 'date', {
            notNull: true,
            codecRef: { codecId: 'pg/date-temporal@1' },
          }),
          col('recipientName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('recipientRole', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reference', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('schoolId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('draft'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('submittedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('subtotalMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('taxMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('totalMinor', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'school_orders_paymentStatus_check_7b9cf2ad',
            "\"paymentStatus\" IN ('unbilled', 'invoiced', 'due_on_delivery', 'paid', 'partially_paid', 'overdue', 'void')",
          ),
          checkExpression(
            'school_orders_paymentTerms_check_9822403d',
            "\"paymentTerms\" IN ('pay_on_delivery', 'prepaid', 'net_7', 'net_14', 'account_credit')",
          ),
          checkExpression(
            'school_orders_status_check_e612ebae',
            "\"status\" IN ('draft', 'submitted', 'under_review', 'confirmed', 'preparing', 'ready_for_delivery', 'out_for_delivery', 'delivered', 'completed', 'change_requested', 'cancelled', 'rejected')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_partners',
        columns: [
          col('address', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('approvedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('classCount', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('deliveryInstructions', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('expectedWeeklyParticipation', 'int4', {
            notNull: true,
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('mainTelephone', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('parish', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('paymentTerms', 'text', {
            notNull: true,
            default: lit('pay_on_delivery'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('pizzaPriceOverrideMinor', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('preferredFrequency', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('principalName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('schoolEmail', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('schoolType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('pending'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('studentPopulation', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('suspendedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'school_partners_paymentTerms_check_9822403d',
            "\"paymentTerms\" IN ('pay_on_delivery', 'prepaid', 'net_7', 'net_14', 'account_credit')",
          ),
          checkExpression(
            'school_partners_status_check_15b10d9d',
            "\"status\" IN ('pending', 'under_review', 'approved', 'rejected', 'suspended')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_payments',
        columns: [
          col('amountMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('currency', 'text', {
            notNull: true,
            default: lit('JMD'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('idempotencyKey', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('invoiceId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('method', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('orderId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('paidAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('recordedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('recordedByName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reference', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('schoolId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_products',
        columns: [
          col('batchSize', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('category', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('JMD'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('imageUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('isActive', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('priceMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('slug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sortOrder', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('validFrom', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('validUntil', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'school_products_category_check_f344fea7',
            "\"category\" IN ('pizza', 'batch')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_programme_events',
        columns: [
          col('actorId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('actorType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('schoolId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_reward_definitions',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('description', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isActive', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('redemptionRules', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('rewardType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('rewardValue', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('scope', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('ticketThreshold', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('validFrom', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('validUntil', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'school_reward_definitions_scope_check_2c8ff566',
            "\"scope\" IN ('class', 'school')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'school_reward_redemptions',
        columns: [
          col('approvedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('approvedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('classId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('idempotencyKey', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('redeemedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('relatedBookingId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('requestedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('rewardDefinitionId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('schoolId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('redemption_requested'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('ticketsConsumed', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'school_reward_redemptions_status_check_cfae3676',
            "\"status\" IN ('locked', 'available', 'redemption_requested', 'approved', 'redeemed', 'rejected')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'visit_day_capacities',
        columns: [
          col('bookingCutoffAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('internalNote', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('maxGuests', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('publicMessage', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reservedGuests', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('open'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('visitDate', 'date', { notNull: true, codecRef: { codecId: 'pg/date-temporal@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'visit_day_capacities_status_check_4a07b314',
            "\"status\" IN ('open', 'limited', 'sold_out', 'closed')",
          ),
        ],
      }),
      this.addUnique({
        schema: 'public',
        table: 'admission_packages',
        constraint: 'admission_packages_slug_key',
        columns: ['slug'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'bookingAdmissionFulfillment',
        constraint: 'bookingAdmissionFulfillment_bookingId_key',
        columns: ['bookingId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'bookingAdmissionFulfillment',
        constraint: 'bookingAdmissionFulfillment_providerEventId_key',
        columns: ['providerEventId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'bookingPassAccess',
        constraint: 'bookingPassAccess_tokenHash_key',
        columns: ['tokenHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'bookingPassAccessSecret',
        constraint: 'bookingPassAccessSecret_accessId_key',
        columns: ['accessId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'bookingPassCredential',
        constraint: 'bookingPassCredential_passId_key',
        columns: ['passId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'booking_extra_definitions',
        constraint: 'booking_extra_definitions_slug_key',
        columns: ['slug'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'booking_package_snapshots',
        constraint: 'booking_package_snapshots_bookingId_key',
        columns: ['bookingId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'booking_passes',
        constraint: 'booking_passes_passNumber_key',
        columns: ['passNumber'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'booking_passes',
        constraint: 'booking_passes_qrTokenHash_key',
        columns: ['qrTokenHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'booking_passes',
        constraint: 'booking_passes_bookingId_sequenceNumber_key',
        columns: ['bookingId', 'sequenceNumber'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'bookings',
        constraint: 'bookings_reference_key',
        columns: ['reference'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'happy_ticket_ledger',
        constraint: 'happy_ticket_ledger_businessKey_key',
        columns: ['businessKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'school_classes',
        constraint: 'school_classes_schoolId_name_key',
        columns: ['schoolId', 'name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'school_invoices',
        constraint: 'school_invoices_orderId_key',
        columns: ['orderId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'school_invoices',
        constraint: 'school_invoices_invoiceNumber_key',
        columns: ['invoiceNumber'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'school_invoices',
        constraint: 'school_invoices_idempotencyKey_key',
        columns: ['idempotencyKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'school_order_class_allocations',
        constraint: 'school_order_class_allocations_orderId_classId_key',
        columns: ['orderId', 'classId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'school_orders',
        constraint: 'school_orders_reference_key',
        columns: ['reference'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'school_orders',
        constraint: 'school_orders_idempotencyKey_key',
        columns: ['idempotencyKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'school_payments',
        constraint: 'school_payments_idempotencyKey_key',
        columns: ['idempotencyKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'school_products',
        constraint: 'school_products_slug_key',
        columns: ['slug'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'school_reward_redemptions',
        constraint: 'school_reward_redemptions_idempotencyKey_key',
        columns: ['idempotencyKey'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'visit_day_capacities',
        constraint: 'visit_day_capacities_visitDate_key',
        columns: ['visitDate'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'admission_package_features',
        index: 'admission_package_features_packageId_idx_51f866f4',
        columns: ['packageId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'admission_package_features',
        index: 'admission_package_features_packageId_sortOrder_idx_1c2cd1c3',
        columns: ['packageId', 'sortOrder'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'admission_packages',
        index: 'admission_packages_isActive_sortOrder_idx_43c1fe34',
        columns: ['isActive', 'sortOrder'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'admission_packages',
        index: 'admission_packages_validFrom_validUntil_idx_377b4d1d',
        columns: ['validFrom', 'validUntil'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookingAdmissionFulfillment',
        index: 'bookingAdmissionFulfillment_providerEventId_idx_0f42ef43',
        columns: ['providerEventId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookingPassAccess',
        index: 'bookingPassAccess_bookingId_idx_17848f4a',
        columns: ['bookingId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookingPassAccess',
        index: 'bookingPassAccess_expiresAt_idx_6b6b8c10',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookingPassAccessSecret',
        index: 'bookingPassAccessSecret_accessId_idx_24f2b174',
        columns: ['accessId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookingPassCredential',
        index: 'bookingPassCredential_passId_idx_09b8dc10',
        columns: ['passId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookingPassSecurityEvent',
        index: 'bookingPassSecurityEvent_bookingId_idx_17848f4a',
        columns: ['bookingId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookingPassSecurityEvent',
        index: 'bookingPassSecurityEvent_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookingPassSecurityEvent',
        index: 'bookingPassSecurityEvent_passId_idx_09b8dc10',
        columns: ['passId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_events',
        index: 'booking_events_bookingId_createdAt_idx_b0a32e18',
        columns: ['bookingId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_events',
        index: 'booking_events_bookingId_idx_17848f4a',
        columns: ['bookingId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_events',
        index: 'booking_events_type_createdAt_idx_00d94001',
        columns: ['type', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_extra_definitions',
        index: 'booking_extra_definitions_isActive_sortOrder_idx_43c1fe34',
        columns: ['isActive', 'sortOrder'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_extras',
        index: 'booking_extras_bookingId_idx_17848f4a',
        columns: ['bookingId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_extras',
        index: 'booking_extras_definitionId_idx_4d3f79b8',
        columns: ['definitionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_guests',
        index: 'booking_guests_bookingId_idx_17848f4a',
        columns: ['bookingId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_guests',
        index: 'booking_guests_guestType_idx_31d4dbc0',
        columns: ['guestType'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_package_snapshots',
        index: 'booking_package_snapshots_admissionPackageId_idx_71108fc3',
        columns: ['admissionPackageId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_passes',
        index: 'booking_passes_bookingId_idx_17848f4a',
        columns: ['bookingId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_passes',
        index: 'booking_passes_bookingId_status_idx_386dff84',
        columns: ['bookingId', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'booking_passes',
        index: 'booking_passes_validDate_status_idx_8ab76ae2',
        columns: ['validDate', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookings',
        index: 'bookings_customerEmail_idx_7ee6d307',
        columns: ['customerEmail'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookings',
        index: 'bookings_customerId_idx_b2a8a46c',
        columns: ['customerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookings',
        index: 'bookings_customerPhone_idx_1a740fd5',
        columns: ['customerPhone'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookings',
        index: 'bookings_paymentStatus_idx_6874c030',
        columns: ['paymentStatus'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'bookings',
        index: 'bookings_visitDate_status_idx_936f87ca',
        columns: ['visitDate', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'check_ins',
        index: 'check_ins_bookingId_scannedAt_idx_6cc80a86',
        columns: ['bookingId', 'scannedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'check_ins',
        index: 'check_ins_passId_idx_09b8dc10',
        columns: ['passId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'check_ins',
        index: 'check_ins_passId_scannedAt_idx_2e9b601b',
        columns: ['passId', 'scannedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'check_ins',
        index: 'check_ins_status_scannedAt_idx_8310ccf5',
        columns: ['status', 'scannedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'happy_ticket_ledger',
        index: 'happy_ticket_ledger_classId_createdAt_idx_14a80a92',
        columns: ['classId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'happy_ticket_ledger',
        index: 'happy_ticket_ledger_classId_idx_0089e5e7',
        columns: ['classId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'happy_ticket_ledger',
        index: 'happy_ticket_ledger_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'happy_ticket_ledger',
        index: 'happy_ticket_ledger_schoolId_createdAt_idx_1d6ae506',
        columns: ['schoolId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'happy_ticket_ledger',
        index: 'happy_ticket_ledger_schoolId_idx_82b454d7',
        columns: ['schoolId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_classes',
        index: 'school_classes_schoolId_idx_82b454d7',
        columns: ['schoolId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_classes',
        index: 'school_classes_schoolId_isActive_idx_567af6bb',
        columns: ['schoolId', 'isActive'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_contacts',
        index: 'school_contacts_schoolId_idx_82b454d7',
        columns: ['schoolId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_contacts',
        index: 'school_contacts_schoolId_isActive_idx_567af6bb',
        columns: ['schoolId', 'isActive'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_invoices',
        index: 'school_invoices_schoolId_idx_82b454d7',
        columns: ['schoolId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_invoices',
        index: 'school_invoices_schoolId_status_idx_7110c695',
        columns: ['schoolId', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_order_class_allocations',
        index: 'school_order_class_allocations_classId_idx_0089e5e7',
        columns: ['classId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_order_class_allocations',
        index: 'school_order_class_allocations_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_order_lines',
        index: 'school_order_lines_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_order_lines',
        index: 'school_order_lines_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_orders',
        index: 'school_orders_paymentStatus_idx_6874c030',
        columns: ['paymentStatus'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_orders',
        index: 'school_orders_pizzaFriday_status_idx_22f0d49d',
        columns: ['pizzaFriday', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_orders',
        index: 'school_orders_schoolId_idx_82b454d7',
        columns: ['schoolId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_orders',
        index: 'school_orders_schoolId_pizzaFriday_idx_c5fc37a1',
        columns: ['schoolId', 'pizzaFriday'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_partners',
        index: 'school_partners_parish_idx_8ffff494',
        columns: ['parish'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_partners',
        index: 'school_partners_status_createdAt_idx_58610442',
        columns: ['status', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_payments',
        index: 'school_payments_invoiceId_idx_d5c4f70e',
        columns: ['invoiceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_payments',
        index: 'school_payments_invoiceId_paidAt_idx_442d0221',
        columns: ['invoiceId', 'paidAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_payments',
        index: 'school_payments_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_payments',
        index: 'school_payments_schoolId_idx_82b454d7',
        columns: ['schoolId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_products',
        index: 'school_products_category_isActive_sortOrder_idx_77af6dd9',
        columns: ['category', 'isActive', 'sortOrder'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_programme_events',
        index: 'school_programme_events_schoolId_createdAt_idx_1d6ae506',
        columns: ['schoolId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_programme_events',
        index: 'school_programme_events_schoolId_idx_82b454d7',
        columns: ['schoolId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_programme_events',
        index: 'school_programme_events_type_createdAt_idx_00d94001',
        columns: ['type', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_reward_definitions',
        index: 'school_rewards_scope_threshold_bb4e3ae2',
        columns: ['scope', 'isActive', 'ticketThreshold'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_reward_redemptions',
        index: 'school_reward_redemptions_classId_idx_0089e5e7',
        columns: ['classId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_reward_redemptions',
        index: 'school_reward_redemptions_rewardDefinitionId_idx_056879cd',
        columns: ['rewardDefinitionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_reward_redemptions',
        index: 'school_reward_redemptions_schoolId_idx_82b454d7',
        columns: ['schoolId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'school_reward_redemptions',
        index: 'school_reward_redemptions_schoolId_status_idx_7110c695',
        columns: ['schoolId', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'visit_day_capacities',
        index: 'visit_day_capacities_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'admission_package_features',
        foreignKey: {
          name: 'admission_package_features_packageId_fkey',
          columns: ['packageId'],
          references: { schema: 'public', table: 'admission_packages', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'bookingAdmissionFulfillment',
        foreignKey: {
          name: 'bookingAdmissionFulfillment_bookingId_fkey',
          columns: ['bookingId'],
          references: { schema: 'public', table: 'bookings', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'bookingPassAccess',
        foreignKey: {
          name: 'bookingPassAccess_bookingId_fkey',
          columns: ['bookingId'],
          references: { schema: 'public', table: 'bookings', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'bookingPassAccessSecret',
        foreignKey: {
          name: 'bookingPassAccessSecret_accessId_fkey',
          columns: ['accessId'],
          references: { schema: 'public', table: 'bookingPassAccess', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'bookingPassCredential',
        foreignKey: {
          name: 'bookingPassCredential_passId_fkey',
          columns: ['passId'],
          references: { schema: 'public', table: 'booking_passes', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'bookingPassSecurityEvent',
        foreignKey: {
          name: 'bookingPassSecurityEvent_passId_fkey',
          columns: ['passId'],
          references: { schema: 'public', table: 'booking_passes', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'booking_events',
        foreignKey: {
          name: 'booking_events_bookingId_fkey',
          columns: ['bookingId'],
          references: { schema: 'public', table: 'bookings', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'booking_extras',
        foreignKey: {
          name: 'booking_extras_bookingId_fkey',
          columns: ['bookingId'],
          references: { schema: 'public', table: 'bookings', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'booking_extras',
        foreignKey: {
          name: 'booking_extras_definitionId_fkey',
          columns: ['definitionId'],
          references: { schema: 'public', table: 'booking_extra_definitions', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'booking_guests',
        foreignKey: {
          name: 'booking_guests_bookingId_fkey',
          columns: ['bookingId'],
          references: { schema: 'public', table: 'bookings', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'booking_package_snapshots',
        foreignKey: {
          name: 'booking_package_snapshots_bookingId_fkey',
          columns: ['bookingId'],
          references: { schema: 'public', table: 'bookings', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'booking_package_snapshots',
        foreignKey: {
          name: 'booking_package_snapshots_admissionPackageId_fkey',
          columns: ['admissionPackageId'],
          references: { schema: 'public', table: 'admission_packages', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'booking_passes',
        foreignKey: {
          name: 'booking_passes_bookingId_fkey',
          columns: ['bookingId'],
          references: { schema: 'public', table: 'bookings', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'check_ins',
        foreignKey: {
          name: 'check_ins_passId_fkey',
          columns: ['passId'],
          references: { schema: 'public', table: 'booking_passes', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'happy_ticket_ledger',
        foreignKey: {
          name: 'happy_ticket_ledger_schoolId_fkey',
          columns: ['schoolId'],
          references: { schema: 'public', table: 'school_partners', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'happy_ticket_ledger',
        foreignKey: {
          name: 'happy_ticket_ledger_classId_fkey',
          columns: ['classId'],
          references: { schema: 'public', table: 'school_classes', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'happy_ticket_ledger',
        foreignKey: {
          name: 'happy_ticket_ledger_orderId_fkey',
          columns: ['orderId'],
          references: { schema: 'public', table: 'school_orders', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_classes',
        foreignKey: {
          name: 'school_classes_schoolId_fkey',
          columns: ['schoolId'],
          references: { schema: 'public', table: 'school_partners', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_contacts',
        foreignKey: {
          name: 'school_contacts_schoolId_fkey',
          columns: ['schoolId'],
          references: { schema: 'public', table: 'school_partners', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_invoices',
        foreignKey: {
          name: 'school_invoices_schoolId_fkey',
          columns: ['schoolId'],
          references: { schema: 'public', table: 'school_partners', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_invoices',
        foreignKey: {
          name: 'school_invoices_orderId_fkey',
          columns: ['orderId'],
          references: { schema: 'public', table: 'school_orders', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_order_class_allocations',
        foreignKey: {
          name: 'school_order_class_allocations_orderId_fkey',
          columns: ['orderId'],
          references: { schema: 'public', table: 'school_orders', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_order_class_allocations',
        foreignKey: {
          name: 'school_order_class_allocations_classId_fkey',
          columns: ['classId'],
          references: { schema: 'public', table: 'school_classes', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_order_lines',
        foreignKey: {
          name: 'school_order_lines_orderId_fkey',
          columns: ['orderId'],
          references: { schema: 'public', table: 'school_orders', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_order_lines',
        foreignKey: {
          name: 'school_order_lines_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'school_products', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_orders',
        foreignKey: {
          name: 'school_orders_schoolId_fkey',
          columns: ['schoolId'],
          references: { schema: 'public', table: 'school_partners', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_payments',
        foreignKey: {
          name: 'school_payments_schoolId_fkey',
          columns: ['schoolId'],
          references: { schema: 'public', table: 'school_partners', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_payments',
        foreignKey: {
          name: 'school_payments_orderId_fkey',
          columns: ['orderId'],
          references: { schema: 'public', table: 'school_orders', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_payments',
        foreignKey: {
          name: 'school_payments_invoiceId_fkey',
          columns: ['invoiceId'],
          references: { schema: 'public', table: 'school_invoices', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_programme_events',
        foreignKey: {
          name: 'school_programme_events_schoolId_fkey',
          columns: ['schoolId'],
          references: { schema: 'public', table: 'school_partners', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_reward_redemptions',
        foreignKey: {
          name: 'school_reward_redemptions_schoolId_fkey',
          columns: ['schoolId'],
          references: { schema: 'public', table: 'school_partners', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_reward_redemptions',
        foreignKey: {
          name: 'school_reward_redemptions_classId_fkey',
          columns: ['classId'],
          references: { schema: 'public', table: 'school_classes', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'school_reward_redemptions',
        foreignKey: {
          name: 'school_reward_redemptions_rewardDefinitionId_fkey',
          columns: ['rewardDefinitionId'],
          references: { schema: 'public', table: 'school_reward_definitions', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
