import { herServices } from "@/lib/her/demo-data";
import type { HerServiceCategory } from "@/lib/her/booking-types";
import { HerAction } from "./her-actions";

const categories: HerServiceCategory[] = ["Signature Experiences", "Hair & Natural Hair", "Advanced Hair & Scalp", "Texture Therapies", "Wellness", "Add-Ons", "Care Programmes"];

export function HerServiceMenu() {
  return <div className="her-surface pb-24 pt-40 text-[#173d32]"><header className="hp-container"><p className="her-kicker">HER service collection · Client preview</p><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-[.95] tracking-[-.05em] sm:text-7xl">Care, thoughtfully composed.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#5d7066]">Explore launch/demo pricing for HER Salon &amp; Wellness at Happy-Park. Final service selection is guided by individual needs and consultation.</p><div className="mt-8 flex flex-wrap gap-3"><HerAction href="/her/book" tone="gold">Start the HER journey</HerAction><HerAction href="#" tone="light" whatsapp>Ask HER</HerAction></div></header>
    <main className="hp-container mt-16 space-y-16">{categories.map((category) => { const items = herServices.filter((item) => item.category === category); const dominant = category === "Signature Experiences" || category === "Care Programmes"; return <section key={category} id={category.toLowerCase().replaceAll(" ", "-").replaceAll("&", "and")}><div className="flex items-end justify-between gap-6 border-b border-[#173d32]/12 pb-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#a47d43]">HER Collection</p><h2 className="mt-2 font-serif text-3xl sm:text-4xl">{category}</h2></div><span className="hidden text-xs font-bold uppercase tracking-[.14em] text-[#6c7b73] sm:block">Demo pricing</span></div><div className={dominant ? "mt-6 grid gap-4 md:grid-cols-2" : "mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"}>{items.map((item) => <article key={item.id} className={dominant ? "rounded-[2rem] bg-[#173d32] p-7 text-white shadow-xl" : "flex min-h-28 items-center justify-between gap-5 rounded-2xl border border-[#173d32]/10 bg-white/70 p-5"}><div><h3 className="font-bold">{item.name}</h3>{item.description ? <p className="mt-3 text-sm leading-6 text-white/60">{item.description}</p> : null}</div><p className={dominant ? "shrink-0 text-sm font-black text-[#dfc48d]" : "shrink-0 text-sm font-black text-[#9b733b]"}>{item.price}</p></article>)}</div>{category === "Advanced Hair & Scalp" ? <p className="mt-5 max-w-4xl text-sm leading-7 text-[#6c7b73]">Advanced services provide care and support for hair and scalp concerns; they do not diagnose or promise medical outcomes. Some concerns may require consultation or referral to an appropriate healthcare professional.</p> : null}{category === "Hair & Natural Hair" ? <p className="mt-5 text-xs leading-6 text-[#6c7b73]">Twist-Out / Braid-Out describes a styling outcome and is not a braid-installation service.</p> : null}</section>})}</main>
  </div>;
}
