import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Award, Building2, Check, GraduationCap, Pizza, Sparkles, Ticket, Truck } from "lucide-react";
import { SCHOOL_PRODUCTS, SCHOOL_PROGRAMME_CONFIG, formatSchoolMoney } from "@/lib/schools/config";

const steps = ["School joins", "School shares the Pizza Friday offer with parents", "School collects parent payments", "Administrator consolidates quantities by class", "School submits one Happy-Park pre-order", "Happy-Park confirms the order", "Happy-Park prepares the bulk order", "Delivery arrives on the agreed Friday", "School pays Happy-Park upon delivery", "Qualifying Happy Tickets are credited", "Class and school progress updates"];
const faqs = [
  ["Who can join?", "Approved infant, primary, infant and primary, preparatory, and other authorized schools."],
  ["How do parents pay?", "The school manages parent collections. Happy-Park does not collect individual payments from children."],
  ["When does the school pay?", "The standard approved term is payment upon delivery, unless another term is authorized in writing."],
  ["How are orders submitted?", "An authorized school administrator submits one consolidated pre-order through the school portal."],
  ["How many pizzas can we order?", "Approved programme limits and availability are shown before submission."],
  ["Can classes order different quantities?", "Yes. Boxes can be allocated by class for aggregate reward accounting—no student names needed."],
  ["Can we choose pizza varieties?", `Yes. The current programme allows up to ${SCHOOL_PROGRAMME_CONFIG.maxPizzaVarieties} varieties per order.`],
  ["How are Happy Tickets earned?", `Qualifying delivered and paid school pizza boxes currently earn ${SCHOOL_PROGRAMME_CONFIG.ticketsPerQualifyingPizza} Happy Tickets each.`],
  ["How do rewards work?", "Configurable class and school rewards unlock for review; eligibility is confirmed before redemption."],
  ["When are pizzas delivered?", "On the approved Friday within the confirmed school delivery window."],
  ["What if our order changes?", "Contact Happy-Park before the cutoff. Confirmed quantities remain subject to School Partner terms."],
  ["How do we become a partner?", "Submit the short school application and Happy-Park will review your programme fit and delivery details."],
];

export function SchoolLanding() {
  const pizzas = SCHOOL_PRODUCTS.filter((p) => p.category === "pizza");
  const batches = SCHOOL_PRODUCTS.filter((p) => p.category === "batch");
  return <div className="overflow-hidden bg-[var(--hp-paper)]">
    <section className="relative min-h-[760px] bg-[var(--hp-forest-deep)] pt-36 text-white">
      <Image src="/images/happy-park/experiences/eat.png" alt="Happy-Park pizza experience" fill priority className="object-cover opacity-25" />
      <div className="absolute inset-0 bg-gradient-to-r from-[var(--hp-forest-deep)] via-[var(--hp-forest-deep)]/90 to-transparent" />
      <div className="hp-container relative grid min-h-[620px] items-center gap-12 py-16 lg:grid-cols-[1.1fr_.9fr]">
        <div><span className="hp-eyebrow !border-white/20 !bg-white/10 !text-white"><GraduationCap className="h-4 w-4" /> Infant & primary schools</span>
          <h1 className="hp-display mt-7 text-6xl font-black sm:text-7xl lg:text-8xl">Pizza Fridays<br/><span className="text-[var(--hp-sun)]">for schools.</span></h1>
          <p className="mt-7 max-w-2xl text-xl font-black uppercase leading-snug tracking-wide sm:text-2xl">Order by the box. Earn by the class. Celebrate as a school.</p>
          <p className="mt-4 text-lg text-white/70">Friday just got happier.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/schools/apply" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-full bg-[var(--hp-sun)] px-7 font-black text-[var(--hp-ink)]">Become a school partner <ArrowRight className="h-5 w-5" /></Link><Link href="/schools/portal/orders/new" className="inline-flex min-h-14 items-center justify-center rounded-full border border-white/25 bg-white/10 px-7 font-bold">Place a school pre-order</Link></div>
        </div>
        <div className="rounded-[36px] border border-white/15 bg-white/10 p-6 backdrop-blur-xl sm:p-8"><div className="flex items-center justify-between"><div><p className="text-sm font-black uppercase tracking-[.18em] text-[var(--hp-lime)]">School Partner Box</p><h2 className="mt-2 text-3xl font-black">14-inch happiness</h2></div><Pizza className="h-14 w-14 text-[var(--hp-sun)]" /></div><div className="mt-8 grid grid-cols-2 gap-3"><Stat value="8" label="slices per pizza"/><Stat value={formatSchoolMoney(250000)} label="proposed school price"/><Stat value="10" label="tickets per box"/><Stat value="1" label="school invoice"/></div><p className="mt-6 rounded-2xl bg-black/20 p-4 text-sm leading-6 text-white/70">Preview programme pricing. Final contracted prices, availability and terms are confirmed for each approved school.</p></div>
      </div>
    </section>

    <section className="hp-section"><div className="hp-container"><Header eyebrow="Simple by design" title="How Pizza Fridays work" copy="One trusted school workflow from parent collections to delivery and rewards. Happy-Park never asks children for payment or personal data."/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{steps.map((step,i)=><div key={step} className="hp-card-hover rounded-[26px] border border-black/10 bg-white p-6"><span className="grid h-10 w-10 place-items-center rounded-full bg-[var(--hp-forest)] text-sm font-black text-white">{i+1}</span><p className="mt-5 font-bold leading-7">{step}</p></div>)}</div></div></section>

    <section className="hp-section bg-[var(--hp-cream)]"><div className="hp-container"><Header eyebrow="Contracted school menu" title="Big boxes. Easy choices." copy={`Every ${SCHOOL_PROGRAMME_CONFIG.pizzaSizeInches}-inch school pizza has ${SCHOOL_PROGRAMME_CONFIG.slicesPerPizza} slices. Prices and products are centrally configurable, with school-specific agreements supported.`}/><div className="mt-12 grid gap-5 lg:grid-cols-3">{pizzas.map(p=><Product key={p.id} icon={<Pizza/>} name={p.name} copy={p.description} meta={`${formatSchoolMoney(p.priceMinor)} · ${p.batchSize} ${p.unitLabel}`}/>)}</div><h3 className="mt-16 text-3xl font-black tracking-tight">Sides and drinks by batch</h3><div className="mt-6 grid gap-5 md:grid-cols-3">{batches.map(p=><Product key={p.id} icon={<Sparkles/>} name={p.name} copy={p.description} meta={`${p.batchSize} ${p.unitLabel} per batch`}/>)}</div></div></section>

    <section className="hp-section bg-[var(--hp-forest)] text-white"><div className="hp-container grid gap-12 lg:grid-cols-2 lg:items-center"><div><span className="hp-eyebrow !border-white/20 !bg-white/10 !text-white"><Ticket className="h-4 w-4"/> Happy Tickets</span><h2 className="hp-heading mt-6 text-5xl font-black sm:text-6xl">Every qualifying box moves your school forward.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">Tickets remain pending until the order is delivered and its payment condition is satisfied. Class and whole-school progress are tracked separately and audibly.</p></div><div className="grid gap-4 sm:grid-cols-2"><Reward icon={<Award/>} title="Happy Start" copy="Recognition and starter rewards."/><Reward icon={<Truck/>} title="Happy Explorer" copy="Experiences and visit benefits."/><Reward icon={<Pizza/>} title="Happy Champion" copy="Pizza Builder celebrations."/><Reward icon={<Building2/>} title="Ultimate Happy Class" copy="Premium class experience eligibility."/></div></div></section>

    <section className="hp-section"><div className="hp-container"><Header eyebrow="Build it. Name it. Eat it." title="The Pizza Builder Challenge" copy="An unlockable class experience using approved crusts, sauces, cheeses and toppings—not weekly custom ordering. Eligibility and safe ingredient availability are always verified."/><div className="mt-12 rounded-[38px] bg-[var(--hp-sun)] p-8 sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><h3 className="text-4xl font-black tracking-tight">Create a class original.</h3><p className="mt-4 max-w-2xl text-lg leading-8">Name it, add an optional slogan, and celebrate the class behind the creation. No child accounts or student contact details required.</p></div><div className="grid h-28 w-28 place-items-center rounded-full bg-white/70"><Pizza className="h-14 w-14 text-[var(--hp-coral)]"/></div></div></div></div></section>

    <section className="hp-section bg-white"><div className="hp-container"><Header eyebrow="Questions from schools" title="Programme FAQ"/><div className="mt-10 grid gap-3 lg:grid-cols-2">{faqs.map(([q,a])=><details key={q} className="group rounded-2xl border border-black/10 bg-[var(--hp-paper)] p-5"><summary className="cursor-pointer list-none font-black">{q}</summary><p className="mt-3 leading-7 text-[var(--hp-ink-soft)]">{a}</p></details>)}</div></div></section>
    <section className="hp-section bg-[var(--hp-coral)]"><div className="hp-container text-center"><h2 className="hp-heading text-5xl font-black text-white sm:text-7xl">Make Friday happier.</h2><p className="mx-auto mt-5 max-w-xl text-lg text-white/85">Join the Happy-Park School Partner Programme in Southfield, St. Elizabeth.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/schools/apply" className="inline-flex min-h-14 items-center justify-center rounded-full bg-white px-8 font-black text-[var(--hp-ink)]">Become a Happy-Park School Partner</Link><Link href="/schools/portal" className="inline-flex min-h-14 items-center justify-center rounded-full border border-white/30 px-8 font-bold text-white">Already a partner? Sign in</Link></div></div></section>
  </div>;
}
function Header({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="max-w-3xl"><span className="hp-eyebrow">{eyebrow}</span><h2 className="hp-heading mt-5 text-5xl font-black sm:text-6xl">{title}</h2>{copy?<p className="hp-copy mt-5 text-lg">{copy}</p>:null}</div>}
function Stat({value,label}:{value:string;label:string}){return <div className="rounded-2xl bg-white/10 p-4"><strong className="block text-2xl font-black">{value}</strong><span className="mt-1 block text-xs uppercase tracking-wide text-white/60">{label}</span></div>}
function Product({icon,name,copy,meta}:{icon:React.ReactNode;name:string;copy:string;meta:string}){return <article className="hp-card-hover rounded-[28px] border border-black/10 bg-white p-7"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-orange-100 text-orange-700">{icon}</div><h3 className="mt-6 text-2xl font-black">{name}</h3><p className="mt-2 leading-7 text-[var(--hp-ink-soft)]">{copy}</p><p className="mt-5 flex items-center gap-2 text-sm font-black text-[var(--hp-forest)]"><Check className="h-4 w-4"/>{meta}</p></article>}
function Reward({icon,title,copy}:{icon:React.ReactNode;title:string;copy:string}){return <div className="rounded-[26px] border border-white/15 bg-white/10 p-6"><div className="text-[var(--hp-sun)]">{icon}</div><h3 className="mt-4 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-white/65">{copy}</p></div>}
