"use client";

import { useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowLeft, ArrowRight, CalendarDays, Check, Clock3, Heart, MessageCircle, RotateCcw, ScanLine, Sparkles, Waves } from "lucide-react";
import Link from "next/link";
import type { HerBookingState, HerIntent } from "@/lib/her/booking-types";
import { getHerRecommendations, getHerService, herDemoSlots } from "@/lib/her/demo-data";
import { createHerJourneyWhatsappUrl } from "@/lib/her/whatsapp";
import { cn } from "@/lib/utils/cn";

const intents = [
  { value: "hair", label: "HAIR", copy: "I want beautiful, healthy hair.", icon: Waves },
  { value: "scalp", label: "SCALP", copy: "I want to care for my scalp and hair health.", icon: ScanLine },
  { value: "wellness", label: "WELLNESS", copy: "I need time to relax and restore.", icon: Sparkles },
  { value: "unsure", label: "I'M NOT SURE", copy: "Help me choose.", icon: MessageCircle },
] as const;

const journeyOptions: Record<HerIntent, { question: string; options: string[] }> = {
  hair: { question: "TELL US ABOUT YOUR HAIR.", options: ["Straight", "Wavy", "Curly", "Coily", "Transitioning", "Children's Hair", "Not Sure"] },
  scalp: { question: "WHAT WOULD YOU LIKE HELP WITH?", options: ["Dry or flaky scalp", "Breakage concerns", "Thinning-hair concerns", "Hair-loss concerns", "Scalp maintenance", "General scalp health", "I'm not sure"] },
  wellness: { question: "HOW WOULD YOU LIKE TO FEEL?", options: ["RELAXED", "RESTORED", "REFRESHED", "COMPLETELY HER"] },
  unsure: { question: "LET'S BEGIN WITH GUIDANCE.", options: ["Hair consultation", "Advanced hair & scalp consultation", "Wellness guidance", "Help me choose"] },
};

const hairNeeds = ["Healthy Hair Maintenance", "Hydration & Moisture", "Strength & Recovery", "Natural Hair Styling", "Silk Press", "Treatment + Style", "Consultation"];
const littleHerNeeds = ["Gentle Wash & Care", "Moisture Treatment", "Natural Hair Care", "Special Occasion Style", "Mom & Me Experience"];

const initialState: HerBookingState = { firstName: "", lastName: "", email: "", phone: "", contactMethod: "WhatsApp", note: "" };

export function HerBookingJourney() {
  const searchParams = useSearchParams();
  const hintedIntent = searchParams.get("intent") as HerIntent | null;
  const hintedService = getHerService(searchParams.get("service") ?? undefined);
  const [booking, setBooking] = useState<HerBookingState>(() => ({ ...initialState, intent: intents.some((item) => item.value === hintedIntent) ? hintedIntent ?? undefined : undefined, recommendation: hintedService?.id }));
  const [step, setStep] = useState(hintedService ? 4 : booking.intent ? 1 : 0);
  const [submitted, setSubmitted] = useState(false);
  const [reference, setReference] = useState("");
  const reduceMotion = useReducedMotion();

  const recommendations = useMemo(() => getHerRecommendations(booking.intent, booking.need).map(getHerService).filter((item): item is NonNullable<typeof item> => Boolean(item)), [booking.intent, booking.need]);
  const selected = getHerService(booking.recommendation);
  const totalSteps = 6;

  function chooseIntent(intent: HerIntent) { setBooking({ ...initialState, intent }); setStep(1); }
  function chooseJourney(value: string) {
    if (booking.intent === "hair" && value === "Children's Hair") { setBooking((current) => ({ ...current, texture: value })); setStep(2); return; }
    if (booking.intent === "hair") { setBooking((current) => ({ ...current, texture: value as HerBookingState["texture"] })); setStep(2); return; }
    setBooking((current) => ({ ...current, need: value })); setStep(3);
  }
  function completeDemo(event: React.FormEvent) { event.preventDefault(); setReference(`HER-DEMO-${Math.random().toString(36).slice(2, 6).toUpperCase()}`); setSubmitted(true); setStep(6); }
  function startOver() { setBooking(initialState); setSubmitted(false); setReference(""); setStep(0); }

  const panel = { initial: reduceMotion ? { opacity: 0 } : { opacity: 0, y: 18 }, animate: { opacity: 1, y: 0 }, exit: reduceMotion ? { opacity: 0 } : { opacity: 0, y: -12 }, transition: { duration: reduceMotion ? 0.01 : .38 } };

  return <div className="her-surface min-h-screen pb-24 pt-36 text-[#173d32] sm:pt-40">
    <div className="hp-container"><header className="mx-auto max-w-3xl text-center"><p className="her-kicker">Interactive concept preview</p><h1 className="mt-5 font-serif text-5xl tracking-[-.05em] sm:text-7xl">The HER Journey</h1><p className="mt-5 text-[#607067]">Your time. Your hair. Your wellness. Your experience.</p></header>
      <div className="mx-auto mt-10 max-w-5xl"><div className="flex items-center justify-between gap-4"><span className="text-xs font-black uppercase tracking-[.14em]">{step === 6 ? "Journey preview complete" : `Step ${Math.min(step + 1, totalSteps)} of ${totalSteps}`}</span><span className="rounded-full border border-[#b38a4d]/20 bg-[#f5ead8] px-3 py-1.5 text-[10px] font-black uppercase tracking-[.14em] text-[#8a6633]">Demo · No live availability</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#173d32]/10"><motion.div className="h-full rounded-full bg-[#b28a4d]" animate={{ width: `${Math.min(((step + 1) / 7) * 100, 100)}%` }} transition={{ duration: reduceMotion ? 0 : .45 }} /></div></div>

      <div className="mx-auto mt-8 min-h-[560px] max-w-5xl overflow-hidden rounded-[2.4rem] border border-[#173d32]/10 bg-white/80 p-6 shadow-[0_30px_100px_rgba(23,61,50,.1)] sm:p-10 lg:p-12">
        <AnimatePresence mode="wait">
          {step === 0 ? <motion.section key="intent" {...panel}><StepHeading eyebrow="Begin" title="WHAT BRINGS YOU TO HER TODAY?" /><div className="mt-10 grid gap-4 sm:grid-cols-2">{intents.map(({ value, label, copy, icon: Icon }) => <ChoiceCard key={value} title={label} copy={copy} icon={<Icon className="h-6 w-6"/>} onClick={() => chooseIntent(value)} />)}</div></motion.section> : null}

          {step === 1 && booking.intent ? <motion.section key="journey" {...panel}><StepHeading eyebrow={booking.intent} title={journeyOptions[booking.intent].question} note={booking.intent === "scalp" ? "Your selections guide a demo recommendation only and do not provide a diagnosis." : undefined} /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{journeyOptions[booking.intent].options.map((option) => <OptionButton key={option} label={option} onClick={() => chooseJourney(option)} />)}</div><Back onClick={() => setStep(0)} /></motion.section> : null}

          {step === 2 ? <motion.section key="needs" {...panel}>{booking.texture === "Children's Hair" || booking.need === "little-her" ? <><p className="text-xs font-black uppercase tracking-[.2em] text-[#b07e70]">Little HER</p><h2 className="mt-4 font-serif text-4xl tracking-[-.04em] sm:text-6xl">Healthy hair.<br/>Happy Little HER.</h2><p className="mt-5 max-w-2xl text-[#607067]">A gentle, premium experience created around healthy hair care and beautiful moments together.</p><p className="mt-8 text-xs font-black uppercase tracking-[.14em]">Little HER hair type</p><div className="mt-3 flex flex-wrap gap-2">{["Straight", "Wavy", "Curly", "Coily", "Mixed Texture", "Not Sure"].map((texture) => <button type="button" key={texture} aria-pressed={booking.texture === texture} onClick={() => setBooking((current) => ({ ...current, texture: texture as HerBookingState["texture"], need: "little-her" }))} className={cn("rounded-full border px-4 py-2 text-sm font-bold", booking.texture === texture && booking.need === "little-her" ? "border-[#173d32] bg-[#173d32] text-white" : "border-[#173d32]/12 bg-white")}>{texture}</button>)}</div><p className="mt-8 text-xs font-black uppercase tracking-[.14em]">Choose an experience</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{littleHerNeeds.map((option) => <OptionButton key={option} label={option} onClick={() => { setBooking((current) => ({ ...current, need: option })); setStep(3); }} />)}</div></> : <><StepHeading eyebrow="Your hair" title="WHAT WOULD YOU LIKE TODAY?"/><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{hairNeeds.map((option) => <OptionButton key={option} label={option} onClick={() => { setBooking((current) => ({ ...current, need: option })); setStep(3); }} />)}</div></>}<Back onClick={() => setStep(1)} /></motion.section> : null}

          {step === 3 ? <motion.section key="recommend" {...panel}><StepHeading eyebrow="Personalized guidance" title="WE THINK YOU'LL LOVE..." note="These suggestions are guidance, not diagnosis or live availability."/><div className="mt-10 grid gap-4 lg:grid-cols-3">{recommendations.map((item) => <button type="button" key={item.id} onClick={() => { setBooking((current) => ({ ...current, recommendation: item.id })); setStep(4); }} className="group flex min-h-64 flex-col rounded-[1.8rem] border border-[#173d32]/10 bg-[#fbf5ea] p-6 text-left transition hover:-translate-y-1 hover:border-[#ad8549]/50 focus-visible:outline focus-visible:outline-3"><span className="text-xs font-black uppercase tracking-[.16em] text-[#a17a42]">{item.category}</span><h3 className="mt-auto font-serif text-3xl">{item.name}</h3><p className="mt-3 text-sm leading-6 text-[#627269]">{item.description ?? "A considered HER experience selected for your journey."}</p><p className="mt-5 font-black">{item.price}</p></button>)}</div><button type="button" onClick={() => setStep(0)} className="mt-8 text-sm font-black underline decoration-[#b28a4d] underline-offset-4">See other experiences</button></motion.section> : null}

          {step === 4 ? <motion.section key="day" {...panel}><StepHeading eyebrow="Demo scheduling" title="YOUR DAY. YOUR TIME." note="Choose a sample date and time for this interactive preview. Slots are not connected to live availability."/><div className="mt-10 grid gap-10 lg:grid-cols-2"><label className="block"><span className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em]"><CalendarDays className="h-4 w-4"/>Your day</span><input type="date" value={booking.date ?? ""} onChange={(event) => setBooking((current) => ({ ...current, date: event.target.value }))} className="mt-4 min-h-14 w-full rounded-2xl border border-[#173d32]/15 bg-[#fffdf8] px-4 font-bold outline-none focus:border-[#b28a4d]"/></label><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em]"><Clock3 className="h-4 w-4"/>Your time · 8AM–8PM daily</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-2">{herDemoSlots.map((slot) => <button type="button" key={slot.value} aria-pressed={booking.time === slot.value} onClick={() => setBooking((current) => ({ ...current, time: slot.value }))} className={cn("min-h-12 rounded-xl border px-3 text-sm font-bold", booking.time === slot.value ? "border-[#173d32] bg-[#173d32] text-white" : "border-[#173d32]/12 bg-white")}>{slot.label}</button>)}</div></div></div><div className="mt-10 flex items-center justify-between"><Back onClick={() => setStep(3)} compact/><button type="button" disabled={!booking.date || !booking.time} onClick={() => setStep(5)} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#173d32] px-6 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-35">Continue <ArrowRight className="h-4 w-4"/></button></div></motion.section> : null}

          {step === 5 ? <motion.form key="details" {...panel} onSubmit={completeDemo}><StepHeading eyebrow="Demo details" title="A FEW DETAILS FOR HER." note="Information stays in this browser session and is not stored or submitted to a booking system."/><div className="mt-9 grid gap-5 sm:grid-cols-2"><Field label="First name" required value={booking.firstName} onChange={(value) => setBooking((c) => ({...c, firstName:value}))}/><Field label="Last name" required value={booking.lastName} onChange={(value) => setBooking((c) => ({...c, lastName:value}))}/><Field label="Email" type="email" required value={booking.email} onChange={(value) => setBooking((c) => ({...c, email:value}))}/><Field label="Phone" type="tel" required value={booking.phone} onChange={(value) => setBooking((c) => ({...c, phone:value}))}/><label className="block"><span className="text-sm font-bold">Preferred contact method</span><select value={booking.contactMethod} onChange={(event) => setBooking((c) => ({...c, contactMethod:event.target.value as HerBookingState["contactMethod"]}))} className="mt-2 min-h-13 w-full rounded-xl border border-[#173d32]/15 bg-white px-4"><option>WhatsApp</option><option>Phone</option><option>Email</option></select></label><label className="block sm:col-span-2"><span className="text-sm font-bold">What would you like HER to know? <span className="font-normal text-[#6b7a72]">(optional, no medical history)</span></span><textarea value={booking.note} onChange={(event) => setBooking((c) => ({...c, note:event.target.value}))} rows={4} className="mt-2 w-full rounded-xl border border-[#173d32]/15 bg-white p-4"/></label></div><div className="mt-10 flex items-center justify-between"><Back onClick={() => setStep(4)} compact/><button type="submit" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#b28a4d] px-6 text-sm font-black text-[#18261f]">Complete preview <Check className="h-4 w-4"/></button></div></motion.form> : null}

          {step === 6 && submitted ? <motion.section key="confirmation" {...panel} className="text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#173d32] text-white"><Heart className="h-7 w-7"/></span><p className="mt-7 text-xs font-black uppercase tracking-[.2em] text-[#a17a42]">Interactive preview</p><h2 className="mt-4 font-serif text-5xl tracking-[-.05em] sm:text-7xl">Your HER journey begins here.</h2><p className="mx-auto mt-5 max-w-xl text-[#627269]">No live appointment has been created. Contact HER to confirm real availability.</p><div className="mx-auto mt-9 max-w-2xl rounded-[1.8rem] bg-[#f6eee0] p-6 text-left"><Summary label="Experience" value={selected?.name ?? "HER consultation"}/><Summary label="Selected day" value={booking.date ?? "Not selected"}/><Summary label="Demo time" value={booking.time ?? "Not selected"}/><Summary label="Price" value={selected?.price ?? "Consultation pricing"}/><Summary label="Guest" value={booking.firstName}/><Summary label="Display-only reference" value={reference}/></div><div className="mt-9 flex flex-wrap justify-center gap-3"><button type="button" onClick={startOver} className="inline-flex min-h-12 items-center gap-2 rounded-full border border-[#173d32]/15 bg-white px-6 text-sm font-black"><RotateCcw className="h-4 w-4"/>Start over</button><Link href="/her/account" className="inline-flex min-h-12 items-center rounded-full bg-[#173d32] px-6 text-sm font-black text-white">View My HER</Link><Link href={createHerJourneyWhatsappUrl(selected?.name, booking.date, booking.time)} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#b28a4d] px-6 text-sm font-black text-[#18261f]"><MessageCircle className="h-4 w-4"/>WhatsApp HER</Link></div></motion.section> : null}
        </AnimatePresence>
      </div>
      <p className="mx-auto mt-6 max-w-3xl text-center text-xs leading-6 text-[#718078]">HER is a front-end concept preview. It does not process payments, reserve appointments, store personal information, or show production availability.</p>
    </div>
  </div>;
}

function StepHeading({ eyebrow, title, note }: { eyebrow: string; title: string; note?: string }) { return <div><p className="text-xs font-black uppercase tracking-[.2em] text-[#a17a42]">{eyebrow}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.04em] sm:text-6xl">{title}</h2>{note ? <p className="mt-5 max-w-2xl text-sm leading-7 text-[#66766d]">{note}</p> : null}</div>; }
function ChoiceCard({ title, copy, icon, onClick }: { title: string; copy: string; icon: React.ReactNode; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex min-h-48 flex-col items-start rounded-[1.7rem] border border-[#173d32]/10 bg-[#fcf8ef] p-6 text-left transition hover:-translate-y-1 hover:border-[#b28a4d]/50 focus-visible:outline focus-visible:outline-3"><span className="text-[#a17a42]">{icon}</span><span className="mt-auto text-xl font-black">{title}</span><span className="mt-2 text-sm text-[#66766d]">{copy}</span></button>; }
function OptionButton({ label, onClick }: { label: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="min-h-16 rounded-2xl border border-[#173d32]/12 bg-[#fffdf8] px-5 text-left text-sm font-bold transition hover:border-[#b28a4d] hover:bg-[#f7eddd] focus-visible:outline focus-visible:outline-3">{label}</button>; }
function Back({ onClick, compact = false }: { onClick: () => void; compact?: boolean }) { return <button type="button" onClick={onClick} className={cn("inline-flex items-center gap-2 text-sm font-black text-[#51655b]", !compact && "mt-9")}><ArrowLeft className="h-4 w-4"/>Back</button>; }
function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (value:string) => void; type?: string; required?: boolean }) { return <label className="block"><span className="text-sm font-bold">{label}</span><input type={type} value={value} required={required} onChange={(event) => onChange(event.target.value)} className="mt-2 min-h-13 w-full rounded-xl border border-[#173d32]/15 bg-white px-4 outline-none focus:border-[#b28a4d]"/></label>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-5 border-b border-[#173d32]/10 py-3 last:border-0"><span className="text-xs font-black uppercase tracking-[.12em] text-[#718078]">{label}</span><span className="text-right font-bold">{value}</span></div>; }
